document handler/force-app/main/default/objects/Document_Checklist__c/Document_Checklist__c.object-meta.xml
<CustomObject>
    <label>Document Checklist</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Document Checklists</relationshipLabel>
    <relationshipName>Document_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Document category - used primarily for reporting</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Photo</fullName>
            </value>
            <value>
                <fullName>Consent Documents</fullName>
            </value>
            <value>
                <fullName>Business Proof Documents</fullName>
            </value>
            <value>
                <fullName>Customer Profile Documents</fullName>
            </value>
            <value>
                <fullName>FD Documents</fullName>
            </value>
            <value>
                <fullName>Other Documents</fullName>
            </value>
            <value>
                <fullName>Insurance Documents</fullName>
            </value>
            <value>
                <fullName>Property Documents</fullName>
                <isActive>false</isActive>
                <label>Property Documents</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Checklist_ID__c.field-meta.xml
<CustomField>
    <fullName>Checklist_ID__c</fullName>
    <description>Used for document upload from CRMNext</description>
    <displayFormat>DOC-{00000000}</displayFormat>
    <externalId>true</externalId>
    <label>Checklist ID</label>
    <type>AutoNumber</type>
</CustomField>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/pdf</fullName>
            </value>
            <value>
                <fullName>image/jpeg</fullName>
            </value>
            <value>
                <fullName>image/png</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>PDf</fullName>
            </value>
            <value>
                <fullName>Doc</fullName>
            </value>
            <value>
                <fullName>text/html</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
                <isActive>false</isActive>
                <label>Text</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Received__c.field-meta.xml
<CustomField>
    <fullName>Received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a document is received. Read only for end user and is automatically populated via content document triggers</description>
    <label>Received?</label>
    <type>Checkbox</type>
</CustomField>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <description>Provision for end user to enter any remarks about the document</description>
    <label>Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the current status of the document</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Waived</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

document handler/force-app/main/default/classes/DocumentUploadControllerTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* @description   :-  Test class for DocumentUploadController
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author        :-  Bhavesh Sharma <bhavesh.sharma@salesforce.com> 
* @author        :-  Udit Singhal <udit.singhal@salesforce.com> 
* @Company       :-  Salesforce
* @version       :-  1.0.0
* @created       :-  10/11/2024
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest
public class DocumentUploadControllerTest {
    @IsTest
    public static void testUploadDocument() {
        Account accRecord = new Account(Name = 'Test Account');
        insert accRecord;
        
        Document_Checklist__c checkListRecord = new Document_Checklist__c();
        checkListRecord.Account__c = accRecord.Id;
        checkListRecord.Document_Name__c = 'Test document.pdf';
        checkListRecord.Category__c = 'Other Documents';
        checkListRecord.Content_Type__c = 'application/pdf';
        checkListRecord.Received__c = true;
        insert checkListRecord;
        
        checkListRecord = [SELECT Id,Document_Name__c,Remarks__c,Content_Type__c,Checklist_ID__c,Status__c
                           FROM Document_Checklist__c
                           LIMIT 1];
        
        Test.startTest();
        DocumentUploadController.uploadDocument('base64 test', accRecord.Id, checkListRecord);
        Test.stopTest();  
        List<Document_Checklist__c> updatedChecklist = [SELECT Id,Document_Name__c,Remarks__c,Content_Type__c,Checklist_ID__c,Status__c
                                                        FROM Document_Checklist__c
                                                       ];
        System.assert(updatedChecklist[0].Document_Name__c != Null,'Document name should not be null');
    }
    
    @IsTest
    public static void testGetCheckists() {
        Test.startTest();
        Account accRecord = new Account(Name = 'Test Account');
        insert accRecord;
        
        Document_Checklist__c checkListRecord = new Document_Checklist__c();
        checkListRecord.Account__c = accRecord.Id;
        checkListRecord.Document_Name__c = 'Test document.pdf';
        checkListRecord.Category__c = 'Other Documents';
        checkListRecord.Content_Type__c = 'application/pdf';
        checkListRecord.Received__c = true;
        insert checkListRecord;
        
        List<Document_Checklist__c> checkLists = DocumentUploadController.getCheckists(accRecord.Id);
        Test.stopTest();
        System.Assert(checkLists.size() > 0);
    }
}