document handler/force-app/main/default/objects/Document_Checklist__c/Document_Checklist__c.object-meta.xml
<CustomObject>
    <label>Document Checklist</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Document Checklists</relationshipLabel>
    <relationshipName>Document_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Document category - used primarily for reporting</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Photo</fullName>
            </value>
            <value>
                <fullName>Consent Documents</fullName>
            </value>
            <value>
                <fullName>Business Proof Documents</fullName>
            </value>
            <value>
                <fullName>Customer Profile Documents</fullName>
            </value>
            <value>
                <fullName>FD Documents</fullName>
            </value>
            <value>
                <fullName>Other Documents</fullName>
            </value>
            <value>
                <fullName>Insurance Documents</fullName>
            </value>
            <value>
                <fullName>Property Documents</fullName>
                <isActive>false</isActive>
                <label>Property Documents</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/pdf</fullName>
            </value>
            <value>
                <fullName>image/jpeg</fullName>
            </value>
            <value>
                <fullName>image/png</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>PDf</fullName>
            </value>
            <value>
                <fullName>Doc</fullName>
            </value>
            <value>
                <fullName>text/html</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
                <isActive>false</isActive>
                <label>Text</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

document handler/force-app/main/default/objects/Document_Checklist__c/fields/Received__c.field-meta.xml
<CustomField>
    <fullName>Received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a document is received. Read only for end user and is automatically populated via content document triggers</description>
    <label>Received?</label>
    <type>Checkbox</type>
</CustomField>

document handler/force-app/main/default/classes/DocumentViewerControllerTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* @description   :-  Controller for DocumentViewerController
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author        :-  Bhavesh Sharma <bhavesh.sharma@salesforce.com> 
* @author        :-  Udit Singhal <udit.singhal@salesforce.com> 
* @Company       :-  Salesforce
* @version       :-  1.0.0
* @created       :-  10/11/2024
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest
public class DocumentViewerControllerTest {
    @IsTest
    public static void testDoCallout() {
        Account accRecord = new Account(Name = 'Test Account');
        insert accRecord;
        
        Document_Checklist__c checkListRecord = new Document_Checklist__c();
        checkListRecord.Account__c = accRecord.Id;
        checkListRecord.Document_Name__c = 'Test document.pdf';
        checkListRecord.Category__c = 'Other Documents';
        checkListRecord.Content_Type__c = 'text/html';
        checkListRecord.Received__c = true;
        insert checkListRecord;
        
        ContentVersion file = new ContentVersion();
        file.Title = 'Test File';
        file.PathOnClient = 'TestFile.txt';
        file.VersionData = Blob.valueOf('Test file contents');
        insert file;
        
        ContentVersion conVersion = [Select ContentDocumentId from ContentVersion where id =: file.Id];
        ContentDocumentLink docLink = new ContentDocumentLink();
        docLink.LinkedEntityId = checkListRecord.Id;
        docLink.ContentDocumentId = conVersion.ContentDocumentId;
        docLink.ShareType = 'V';
        insert docLink;
        
        Test.startTest();
        DocumentViewerController.ResultWrapper pdf = DocumentViewerController.doCallout(checkListRecord.Id)    ;
        Test.stopTest();
        
        // asserting that doc Content which is returned in pdf variable is not null
        System.assertNotEquals(null, pdf);
    }
    
    @IsTest
    public static void testGetDocument() {
        Account accRecord = new Account(Name = 'Test Account');
        insert accRecord;
        
        Document_Checklist__c checkListRecord = new Document_Checklist__c();
        checkListRecord.Account__c = accRecord.Id;
        checkListRecord.Document_Name__c = 'Test document.pdf';
        checkListRecord.Category__c = 'Other Documents';
        checkListRecord.Content_Type__c = 'application/pdf';
        checkListRecord.Received__c = true;
        insert checkListRecord;
        
        ContentVersion file = new ContentVersion();
        file.Title = 'Test File';
        file.PathOnClient = 'TestFile.txt';
        file.VersionData = Blob.valueOf('Test file contents');
        insert file;
        
        ContentVersion conVersion = [Select ContentDocumentId from ContentVersion where id =: file.Id];
        ContentDocumentLink docLink = new ContentDocumentLink();
        docLink.LinkedEntityId = checkListRecord.Id;
        docLink.ContentDocumentId = conVersion.ContentDocumentId;
        docLink.ShareType = 'V';
        insert docLink;
        
        Test.startTest();
        DocumentViewerController.ResultWrapper pdf = DocumentViewerController.getDocument(checkListRecord.Id)    ;
        Test.stopTest();
        
        // asserting that doc Content which is returned in pdf variable is not null
        System.assertNotEquals(null, pdf);
    }
}